### PR TITLE
Ensure IO is GC preserved while used

### LINKED ISSUE #31: GC error (EXCEPTION_ACCESS_VIOLATION) from libpng.dll?
While trying to display a bunch of images sequentially (like a movie) in Pluto.jl, I've been getting occasional (hard-to-reproduce) crashes on Windows 10, Julia 1.6-beta, PNGFiles.jl 0.3.5. I'm not even sure where to start with this stacktrace:
```
      From worker 6:
      From worker 6:    Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
      From worker 6:    Exception: EXCEPTION_ACCESS_VIOLATION at 0x278a061 -- jl_object_id_ at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:366 [inlined]
      From worker 6:    jl_object_id_ at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:343 [inlined]
      From worker 6:    jl_object_id at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:373
      From worker 6:    in expression starting at none:1
      From worker 6:    jl_object_id_ at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:366 [inlined]
      From worker 6:    jl_object_id_ at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:343 [inlined]
      From worker 6:    jl_object_id at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:373
      From worker 6:    type_hash at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:981
      From worker 6:    typekey_hash at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:993 [inlined]
      From worker 6:    lookup_type at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:585
      From worker 6:    inst_datatype_inner at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:1157
      From worker 6:    jl_inst_arg_tuple_type at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:1424
      From worker 6:    arg_type_tuple at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1823 [inlined]
      From worker 6:    jl_lookup_generic_ at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2350
      From worker 6:    jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2402
      From worker 6:    _writecallback at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:422
      From worker 6:    unknown function (ip: 0000000001338805)
      From worker 6:    .text at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_chunk_header at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_complete_chunk at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_compress_IDAT at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_filtered_row at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_find_filter at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_row at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_image at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    _write_image at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:426 [inlined]
      From worker 6:    #_save#15 at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:414
      From worker 6:    _save##kw at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:344
      From worker 6:    #13 at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:326
      From worker 6:    maybe_lock at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:36 [inlined]
      From worker 6:    maybe_lock at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:38 [inlined]
      From worker 6:    #save#12 at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:323
      From worker 6:    save at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:315
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:686 [inlined]
      From worker 6:    jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:722
      From worker 6:    #invokelatest#2 at .\essentials.jl:707
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    invokelatest at .\essentials.jl:706
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    #save#7 at C:\Users\alexa\.julia\packages\ImageIO\uPn5K\src\ImageIO.jl:46
      From worker 6:    save##kw at C:\Users\alexa\.julia\packages\ImageIO\uPn5K\src\ImageIO.jl:41
      From worker 6:    inner at .\essentials.jl:710
      From worker 6:    unknown function (ip: 0000000001336633)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:686 [inlined]
      From worker 6:    jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:722
      From worker 6:    #invokelatest#2 at .\essentials.jl:711
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    invokelatest##kw at .\essentials.jl:706
      From worker 6:    #save#33 at C:\Users\alexa\.julia\packages\FileIO\TyKdX\src\loadsave.jl:233
      From worker 6:    save##kw at C:\Users\alexa\.julia\packages\FileIO\TyKdX\src\loadsave.jl:217
      From worker 6:    #show#13 at C:\Users\alexa\.julia\packages\ImageShow\9kpaq\src\showmime.jl:43
      From worker 6:    unknown function (ip: 000000000134af2b)
      From worker 6:    show at C:\Users\alexa\.julia\packages\ImageShow\9kpaq\src\showmime.jl:28
      From worker 6:    unknown function (ip: 000000000134a684)
      From worker 6:    show_richest at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:601
      From worker 6:    unknown function (ip: 000000005f3455b4)
      From worker 6:    #sprint_withreturned#28 at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:549
      From worker 6:    sprint_withreturned##kw at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:548
      From worker 6:    unknown function (ip: 000000000134a398)
      From worker 6:    format_output_default at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:474
      From worker 6:    #format_output#17 at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:491 [inlined]
      From worker 6:    format_output##kw at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:491
      From worker 6:    unknown function (ip: 000000005f341e04)
      From worker 6:    formatted_result_of at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:416
      From worker 6:    unknown function (ip: 000000005f337666)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:115
      From worker 6:    eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:204
      From worker 6:    eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:155 [inlined]
      From worker 6:    eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:575
      From worker 6:    jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:669
      From worker 6:    jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:879
      From worker 6:    jl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:888 [inlined]
      From worker 6:    jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:931
      From worker 6:    eval at .\boot.jl:360
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    #106 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278
      From worker 6:    run_work_thunk at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
      From worker 6:    macro expansion at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278 [inlined]
      From worker 6:    #105 at .\task.jl:406
      From worker 6:    unknown function (ip: 000000005f330ae3)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:839
      From worker 6:    Allocations: 266574933 (Pool: 266499444; Big: 75489); GC: 232
      From worker 6:    GC error (probable corruption) :
      From worker 6:    Allocations: 266913264 (Pool: 266837633; Big: 75631); GC: 232
      From worker 6:    <?#000000007c589f80::0000000000000000>
      From worker 6:    0000000091007040: Queued root: 000000001b8a0970 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007058: Queued root: 000000001d089ed0 :: 0000000010348fb0 (bits: 3)
      From worker 6:            of type Base.IdDict{Any, Any}
      From worker 6:    0000000091007070: Queued root: 0000000019b30650 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007088: Queued root: 0000000013500c70 :: 000000001072fd50 (bits: 3)
      From worker 6:            of type Base.Dict{Distributed.RRID, Any}
      From worker 6:    00000000910070a0: Queued root: 000000007a011f50 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910070b8: Queued root: 000000007a31d910 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910070d0: Queued root: 00000000b2052240 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910070e8: Queued root: 00000000b205a140 :: 000000001a4ff850 (bits: 3)
      From worker 6:            of type Array{Base.Dict{Tuple{UInt64, Int64}, Int64}, 1}
      From worker 6:    0000000091007100: Queued root: 000000001d180eb0 :: 0000000010115cb0 (bits: 3)
      From worker 6:            of type Module
      From worker 6:    0000000091007118: Queued root: 000000001c8f9910 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007130: Queued root: 000000007ab5f5a0 :: 00000000102b74d0 (bits: 3)
      From worker 6:            of type Core.Box
      From worker 6:    0000000091007148: Queued root: 0000000013daf330 :: 0000000010348fb0 (bits: 3)
      From worker 6:            of type Base.IdDict{Any, Any}
      From worker 6:    0000000091007160: Queued root: 000000001c743080 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007178: Queued root: 000000001028f900 :: 0000000010115cb0 (bits: 3)
      From worker 6:            of type Module
      From worker 6:    0000000091007190: Queued root: 0000000019c40010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910071a8: Queued root: 000000008270dc30 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910071c0: Queued root: 0000000019c3c010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910071d8: Queued root: 000000008270d910 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910071f0: Queued root: 0000000019c38010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007208: Queued root: 000000008270e590 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007220: Queued root: 0000000019c34010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007238: Queued root: 000000008270ddc0 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007250: Queued root: 0000000019c30010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007268: Queued root: 000000008270d5f0 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007280: Queued root: 0000000019c2c010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    0000000091007298: Queued root: 000000008270daa0 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910072b0: Queued root: 0000000019c28010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910072c8: Queued root: 000000008270e0e0 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910072e0: Queued root: 0000000019b30010 :: 0000000010361610 (bits: 3)
      From worker 6:            of type Task
      From worker 6:    00000000910072f8: Queued root: 000000001c4511f0 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007310: Queued root: 00000000818be470 :: 0000000010115e80 (bits: 3)
      From worker 6:            of type Core.MethodTable
      From worker 6:    0000000091007328: Queued root: 000000001c666ab0 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007340: Queued root: 0000000081953cd0 :: 0000000010115e80 (bits: 3)
      From worker 6:            of type Core.MethodTable
      From worker 6:    0000000091007358: Queued root: 00000000101453c0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007370: Queued root: 000000007b10a6d0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007388: Queued root: 000000009d9cf480 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910073a0: Queued root: 0000000012a450c0 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    00000000910073b8: Queued root: 000000009e556240 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910073d0: Queued root: 000000007c492210 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910073e8: Queued root: 00000000b21c36c0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007400: Queued root: 0000000012a448f0 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007418: Queued root: 000000001bb16590 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007430: Queued root: 000000007c73acb0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007448: Queued root: 000000001cff0bf0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007460: Queued root: 0000000012a443b0 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007478: Queued root: 0000000012a51980 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007490: Queued root: 0000000012a4ab70 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910074a8: Queued root: 00000000120f0fa0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910074c0: Queued root: 0000000011ccfa30 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910074d8: Queued root: 0000000013b133a0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910074f0: Queued root: 00000000b23de700 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007508: Queued root: 000000008a3ffda0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007520: Queued root: 0000000011ccee40 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007538: Queued root: 000000007a2d44a0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007550: Queued root: 0000000011cb4d20 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007568: Queued root: 0000000084917eb0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007580: Queued root: 00000000133fbc70 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007598: Queued root: 000000001248a430 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910075b0: Queued root: 0000000010b3ffa0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910075c8: Queued root: 000000001b7eafb0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910075e0: Queued root: 0000000011ca11e0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910075f8: Queued root: 0000000012fc93c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007610: Queued root: 0000000011f7efa0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007628: Queued root: 0000000013064aa0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007640: Queued root: 000000001374dcf0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007658: Queued root: 000000001c666c10 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007670: Queued root: 0000000081953df0 :: 0000000010115e80 (bits: 3)
      From worker 6:            of type Core.MethodTable
      From worker 6:    0000000091007688: Queued root: 0000000011515760 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    00000000910076a0: Queued root: 000000008c41c930 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910076b8: Queued root: 000000008c78a620 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910076d0: Queued root: 0000000011515440 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910076e8: Queued root: 00000000882b1ba0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007700: Queued root: 0000000010cd1730 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007718: Queued root: 000000007cc90bb0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007730: Queued root: 00000000a43d0ec0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007748: Queued root: 000000007e2e2800 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007760: Queued root: 000000001d870240 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007778: Queued root: 000000007e55d8c0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007790: Queued root: 000000007e4c2740 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910077a8: Queued root: 000000001cc63f30 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910077c0: Queued root: 00000000ab402180 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910077d8: Queued root: 000000007e4d2500 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910077f0: Queued root: 000000007e2daf80 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007808: Queued root: 000000001b3a2fe0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007820: Queued root: 000000009d291780 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007838: Queued root: 0000000067b6ff80 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007850: Queued root: 0000000011c688b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007868: Queued root: 00000000132d7d20 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007880: Queued root: 0000000014470020 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007898: Queued root: 00000000117e8f20 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910078b0: Queued root: 000000009da91a00 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910078c8: Queued root: 0000000067b74040 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910078e0: Queued root: 0000000010484310 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    00000000910078f8: Queued root: 00000000131b8950 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007910: Queued root: 00000000852ea920 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007928: Queued root: 000000007eee46c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007940: Queued root: 000000006798c0c0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007958: Queued root: 00000000b56abf80 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007970: Queued root: 00000000231184c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007988: Queued root: 0000000085302490 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910079a0: Queued root: 00000000b27cebc0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910079b8: Queued root: 00000000796b3b60 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910079d0: Queued root: 000000009d9bbe80 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910079e8: Queued root: 00000000ab4c0c00 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007a00: Queued root: 000000009e8c4080 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007a18: Queued root: 0000000012b45ce0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007a30: Queued root: 0000000082efe490 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007a48: Queued root: 000000009e8c8140 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007a60: Queued root: 000000007a2316e0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007a78: Queued root: 00000000106e94d0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007a90: Queued root: 0000000012845af0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007aa8: Queued root: 00000000132b3f50 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007ac0: Queued root: 0000000085302920 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007ad8: Queued root: 000000007ebffec0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007af0: Queued root: 0000000082bc6650 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007b08: Queued root: 0000000014509d60 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007b20: Queued root: 000000001d642cb0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007b38: Queued root: 00000000ab1df280 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007b50: Queued root: 0000000082effb60 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007b68: Queued root: 00000000ab4c5280 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007b80: Queued root: 000000001317c900 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007b98: Queued root: 000000001318c160 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007bb0: Queued root: 00000000105ad290 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007bc8: Queued root: 0000000011524df0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007be0: Queued root: 00000000112e6340 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007bf8: Queued root: 0000000012492620 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007c10: Queued root: 00000000121dde10 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007c28: Queued root: 0000000012a022a0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007c40: Queued root: 000000001151e980 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007c58: Queued root: 0000000084917790 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007c70: Queued root: 000000001169ed30 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007c88: Queued root: 0000000084917c70 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007ca0: Queued root: 000000001151a7a0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007cb8: Queued root: 000000001b6ef8b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007cd0: Queued root: 000000001151a050 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007ce8: Queued root: 000000008369fc70 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d00: Queued root: 0000000010b3c6d0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d18: Queued root: 000000008ca28710 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d30: Queued root: 000000001d9f4850 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d48: Queued root: 0000000011e78bd0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d60: Queued root: 000000008ca28630 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d78: Queued root: 000000001c77b090 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007d90: Queued root: 0000000013501c50 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007da8: Queued root: 0000000013501b10 :: 0000000010115e80 (bits: 3)
      From worker 6:            of type Core.MethodTable
      From worker 6:    0000000091007dc0: Queued root: 000000002291f1c0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007dd8: Queued root: 000000007e58b100 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007df0: Queued root: 0000000014873950 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007e08: Queued root: 000000007d9c7f40 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007e20: Queued root: 000000007e589ac0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007e38: Queued root: 000000001461c0b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007e50: Queued root: 0000000011b397a0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007e68: Queued root: 0000000013504500 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007e80: Queued root: 0000000013504320 :: 0000000010115e80 (bits: 3)
      From worker 6:            of type Core.MethodTable
      From worker 6:    0000000091007e98: Queued root: 000000001355cf90 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007eb0: Queued root: 0000000013583f60 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007ec8: Queued root: 000000001355cee0 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091007ee0: Queued root: 000000009df8a400 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007ef8: Queued root: 0000000013c50f50 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007f10: Queued root: 0000000011540170 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007f28: Queued root: 00000000119d0a10 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007f40: Queued root: 00000000145de000 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007f58: Queued root: 000000001b6b17d0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007f70: Queued root: 000000001abdc160 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091007f88: Queued root: 000000001b0da4f0 :: 0000000010246c10 (bits: 3)
      From worker 6:            of type Core.MethodInstance
      From worker 6:    0000000091007fa0: Queued root: 000000001b0da2c0 :: 0000000010246c10 (bits: 3)
      From worker 6:            of type Core.MethodInstance
      From worker 6:    0000000091007fb8: Queued root: 000000001b04d9b0 :: 0000000010246c10 (bits: 3)
      From worker 6:            of type Core.MethodInstance
      From worker 6:    0000000091007fd0: Queued root: 000000001ab88240 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091007fe8: Queued root: 000000001a408a90 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008000: Queued root: 000000007d9dd440 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008018: Queued root: 000000007e2debc0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008030: Queued root: 000000009fae0d80 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008048: Queued root: 000000007d8e1600 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008060: Queued root: 0000000022af6200 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008078: Queued root: 000000009ffd4080 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008090: Queued root: 00000000b24422c0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910080a8: Queued root: 0000000013160af0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910080c0: Queued root: 00000000130ab4e0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910080d8: Queued root: 0000000012b7b0c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910080f0: Queued root: 0000000011ecaf00 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008108: Queued root: 000000001b9c48b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008120: Queued root: 0000000011ece040 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008138: Queued root: 0000000011b37f30 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008150: Queued root: 000000001052c8c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008168: Queued root: 0000000010445a30 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008180: Queued root: 0000000086c84d90 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008198: Queued root: 0000000012d869c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910081b0: Queued root: 00000000127e03b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910081c8: Queued root: 00000000118a6950 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910081e0: Queued root: 000000001456f4b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910081f8: Queued root: 0000000013726df0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008210: Queued root: 000000001349cbd0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008228: Queued root: 000000001bb0cf10 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008240: Queued root: 000000001197a950 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008258: Queued root: 0000000012aacda0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008270: Queued root: 00000000126fa390 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008288: Queued root: 000000001245b9d0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910082a0: Queued root: 00000000134b00e0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910082b8: Queued root: 00000000134b2bc0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910082d0: Queued root: 0000000012233ec0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910082e8: Queued root: 0000000012f91c50 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008300: Queued root: 00000000114129f0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008318: Queued root: 0000000011412c10 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008330: Queued root: 000000001bb0cf70 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008348: Queued root: 000000001bb0cfd0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008360: Queued root: 000000001279dd90 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008378: Queued root: 00000000127c10f0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008390: Queued root: 000000001bb0d030 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910083a8: Queued root: 000000001bb0d090 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910083c0: Queued root: 000000001bb0d0f0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910083d8: Queued root: 000000001197a6e0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910083f0: Queued root: 0000000014093c10 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008408: Queued root: 00000000128498a0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008420: Queued root: 0000000013267590 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008438: Queued root: 000000001b6cd510 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008450: Queued root: 000000001bb0d1b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008468: Queued root: 00000000119c1ca0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008480: Queued root: 0000000012826f80 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008498: Queued root: 00000000119248d0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910084b0: Queued root: 0000000012081750 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910084c8: Queued root: 000000001bb0d330 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910084e0: Queued root: 000000001bb0d390 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910084f8: Queued root: 000000001bb0d3f0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008510: Queued root: 00000000133fc920 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008528: Queued root: 0000000014537390 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008540: Queued root: 0000000012d98fc0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008558: Queued root: 0000000012d92640 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008570: Queued root: 00000000135048c0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008588: Queued root: 000000001bc8a290 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910085a0: Queued root: 000000007ae06890 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910085b8: Queued root: 000000001251eab0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910085d0: Queued root: 000000001bb6a3b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910085e8: Queued root: 00000000114102b0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008600: Queued root: 0000000012e13350 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008618: Queued root: 000000001bb6a470 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008630: Queued root: 0000000013504630 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008648: Queued root: 0000000011f07060 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008660: Queued root: 000000001139f470 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008678: Queued root: 00000000796b1b70 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008690: Queued root: 000000001341af40 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910086a8: Queued root: 000000001341aa10 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910086c0: Queued root: 0000000011e70ba0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910086d8: Queued root: 000000007b2cc430 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910086f0: Queued root: 0000000011b5ee40 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008708: Queued root: 000000008747fb60 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008720: Queued root: 0000000012234500 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091008738: Queued root: 00000000852e8010 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    0000000091008750: Queued root: 0000000013546b40 :: 00000000102467d0 (bits: 3)
      From worker 6:            of type Method
      From worker 6:    0000000091008768: Queued root: 00000000135461d0 :: 0000000010115e80 (bits: 3)
      From worker 6:            of type Core.MethodTable
      From worker 6:    0000000091008780: Queued root: 0000000013544c90 :: 0000000010112160 (bits: 3)
      From worker 6:            of type Core.TypeName
      From worker 6:    0000000091008798: Queued root: 000000001bef1250 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910087b0: Queued root: 000000001bef16e0 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910087c8: Queued root: 000000001bef1b70 :: 0000000010115d70 (bits: 3)
      From worker 6:            of type Core.SimpleVector
      From worker 6:    00000000910087e0: Queued root: 00000000148a5d20 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910087f8: Queued root: 00000000148c0500 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008810: Queued root: 00000000116f2e20 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008828: Queued root: 0000000013546c80 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008840: Queued root: 000000001279e430 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008858: Queued root: 00000000116f6910 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008870: Queued root: 0000000010aab950 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008888: Queued root: 00000000133d7940 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910088a0: Queued root: 0000000013501e00 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910088b8: Queued root: 000000001ba56530 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910088d0: Queued root: 000000001bc27190 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    00000000910088e8: Queued root: 0000000010b7e470 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008900: Queued root: 0000000010591b70 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008918: Queued root: 000000001223c550 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008930: Queued root: 0000000012f98be0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008948: Queued root: 0000000011b30ae0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008960: Queued root: 00000000134fb5f0 :: 0000000010116430 (bits: 3)
      From worker 6:            of type Array{Any, 1}
      From worker 6:    0000000091008978: Root object: 000000007a3a8e40 :: 00000000101160c0 (bits: 1)
      From worker 6:            of type Int64
      From worker 6:    0000000091008990:  r-- Stack frame 0000000061d6cfc0 -- 0 of 36 (direct)
      From worker 6:
      From worker 6:    signal (22): SIGABRT
      From worker 6:    in expression starting at none:1
      From worker 6:    crt_sig_handler at /cygdrive/c/buildbot/worker/package_win64/build/src\signals-win.c:93
      From worker 6:    raise at C:\WINDOWS\System32\msvcrt.dll (unknown line)
      From worker 6:    abort at C:\WINDOWS\System32\msvcrt.dll (unknown line)
      From worker 6:    gc_assert_datatype_fail at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1622
      From worker 6:    gc_mark_loop at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:2685
      From worker 6:    _jl_gc_collect at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3006
      From worker 6:    jl_gc_collect at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3213
      From worker 6:    gc at .\gcutils.jl:94 [inlined]
      From worker 6:    #temp_cleanup_purge#15 at .\file.jl:515
      From worker 6:    temp_cleanup_purge##kw at .\file.jl:511 [inlined]
      From worker 6:    #787 at .\initdefs.jl:322
      From worker 6:    jfptr_YY.787_25025.clone_1 at C:\Users\alexa\AppData\Local\Programs\Julia-1.6.0-beta1\lib\julia\sys.dll (unknown line)
      From worker 6:    _atexit at .\initdefs.jl:343
      From worker 6:    jfptr__atexit_44479.clone_1 at C:\Users\alexa\AppData\Local\Programs\Julia-1.6.0-beta1\lib\julia\sys.dll (unknown line)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    jl_atexit_hook at /cygdrive/c/buildbot/worker/package_win64/build/src\init.c:223
      From worker 6:    jl_exit at /cygdrive/c/buildbot/worker/package_win64/build/src\jl_uv.c:632
      From worker 6:    jl_exception_handler at /cygdrive/c/buildbot/worker/package_win64/build/src\signals-win.c:318
      From worker 6:    __julia_personality at /cygdrive/c/buildbot/worker/package_win64/build/src/support\win32_ucontext.c:28
      From worker 6:    _chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
      From worker 6:    RtlImageRvaToSection at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
      From worker 6:    KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
      From worker 6:    jl_object_id_ at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:359 [inlined]
      From worker 6:    jl_object_id_ at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:343 [inlined]
      From worker 6:    jl_object_id at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:373
      From worker 6:    type_hash at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:981
      From worker 6:    typekey_hash at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:993 [inlined]
      From worker 6:    lookup_type at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:585
      From worker 6:    inst_datatype_inner at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:1157
      From worker 6:    jl_inst_arg_tuple_type at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:1424
      From worker 6:    arg_type_tuple at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1823 [inlined]
      From worker 6:    jl_lookup_generic_ at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2350
      From worker 6:    jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2402
      From worker 6:    _writecallback at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:422
      From worker 6:    unknown function (ip: 0000000001338805)
      From worker 6:    .text at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_chunk_header at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_complete_chunk at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_compress_IDAT at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_filtered_row at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_find_filter at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_row at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    png_write_image at C:\Users\alexa\.julia\artifacts\0407eb942f4c6c53c9bcc1eeccf3def7b46d6cc7\bin\libpng16.dll (unknown line)
      From worker 6:    _write_image at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:426 [inlined]
      From worker 6:    #_save#15 at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:414
      From worker 6:    _save##kw at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:344
      From worker 6:    #13 at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:326
      From worker 6:    maybe_lock at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:36 [inlined]
      From worker 6:    maybe_lock at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:38 [inlined]
      From worker 6:    #save#12 at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:323
      From worker 6:    save at C:\Users\alexa\.julia\packages\PNGFiles\CQUsD\src\io.jl:315
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:686 [inlined]
      From worker 6:    jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:722
      From worker 6:    #invokelatest#2 at .\essentials.jl:707
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    invokelatest at .\essentials.jl:706
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    #save#7 at C:\Users\alexa\.julia\packages\ImageIO\uPn5K\src\ImageIO.jl:46
      From worker 6:    save##kw at C:\Users\alexa\.julia\packages\ImageIO\uPn5K\src\ImageIO.jl:41
      From worker 6:    inner at .\essentials.jl:710
      From worker 6:    unknown function (ip: 0000000001336633)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:686 [inlined]
      From worker 6:    jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:722
      From worker 6:    #invokelatest#2 at .\essentials.jl:711
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    invokelatest##kw at .\essentials.jl:706
      From worker 6:    #save#33 at C:\Users\alexa\.julia\packages\FileIO\TyKdX\src\loadsave.jl:233
      From worker 6:    save##kw at C:\Users\alexa\.julia\packages\FileIO\TyKdX\src\loadsave.jl:217
      From worker 6:    #show#13 at C:\Users\alexa\.julia\packages\ImageShow\9kpaq\src\showmime.jl:43
      From worker 6:    unknown function (ip: 000000000134af2b)
      From worker 6:    show at C:\Users\alexa\.julia\packages\ImageShow\9kpaq\src\showmime.jl:28
      From worker 6:    unknown function (ip: 000000000134a684)
      From worker 6:    show_richest at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:601
      From worker 6:    unknown function (ip: 000000005f3455b4)
      From worker 6:    #sprint_withreturned#28 at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:549
      From worker 6:    sprint_withreturned##kw at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:548
      From worker 6:    unknown function (ip: 000000000134a398)
      From worker 6:    format_output_default at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:474
      From worker 6:    #format_output#17 at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:491 [inlined]
      From worker 6:    format_output##kw at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:491
      From worker 6:    unknown function (ip: 000000005f341e04)
      From worker 6:    formatted_result_of at C:\Users\alexa\.julia\packages\Pluto\luIaC\src\runner\PlutoRunner.jl:416
      From worker 6:    unknown function (ip: 000000005f337666)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:115
      From worker 6:    eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:204
      From worker 6:    eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:155 [inlined]
      From worker 6:    eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:575
      From worker 6:    jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:669
      From worker 6:    jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:879
      From worker 6:    jl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:888 [inlined]
      From worker 6:    jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:931
      From worker 6:    eval at .\boot.jl:360
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:672
      From worker 6:    #106 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278
      From worker 6:    run_work_thunk at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
      From worker 6:    macro expansion at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278 [inlined]
      From worker 6:    #105 at .\task.jl:406
      From worker 6:    unknown function (ip: 000000005f330ae3)
      From worker 6:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 6:    start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:839
      From worker 6:    Allocations: 266913264 (Pool: 266837633; Big: 75631); GC: 232
Worker 6 terminated.Distributed
.ProcessExitedException(6)
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base .\task.jl:705
  [2] wait
    @ .\task.jl:764 [inlined]
  [3] wait(c::Base.GenericCondition{ReentrantLock})
    @ Base .\condition.jl:106
  [4] take_buffered(c::Channel{Any})
    @ Base .\channels.jl:389
  [5] take!(c::Channel{Any})
    @ Base .\channels.jl:383
  [6] take!(::Distributed.RemoteValue)
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\remotecall.jl:599
  [7] remotecall_fetch(::Function, ::Distributed.Worker, ::Module, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\remotecall.jl:390
  [8] remotecall_fetch(::Function, ::Distributed.Worker, ::Module, ::Vararg{Any, N} where N)
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\remotecall.jl:386
  [9] #remotecall_fetch#146
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\remotecall.jl:421 [inlined]
 [10] remotecall_fetch
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\remotecall.jl:421 [inlined]
 [11] remotecall_eval
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\macros.jl:246 [inlined]
 [12] (::Pluto.WorkspaceManager.var"#12#13"{Base.UUID, Bool, Nothing, Pluto.WorkspaceManager.Workspace})()
    @ Pluto.WorkspaceManager ~\.julia\packages\Pluto\luIaC\src\evaluation\WorkspaceManager.jl:260
 [13] withtoken(f::Pluto.WorkspaceManager.var"#12#13"{Base.UUID, Bool, Nothing, Pluto.WorkspaceManager.Workspace}, token::Pluto.Token)
    @ Pluto ~\.julia\packages\Pluto\luIaC\src\evaluation\Tokens.jl:18
 [14] format_fetch_in_workspace
    @ ~\.julia\packages\Pluto\luIaC\src\evaluation\WorkspaceManager.jl:259 [inlined]
 [15] format_fetch_in_workspace
    @ ~\.julia\packages\Pluto\luIaC\src\evaluation\WorkspaceManager.jl:256 [inlined]
 [16] eval_format_fetch_in_workspace(session_notebook::Tuple{Pluto.ServerSession, Pluto.Notebook}, expr::Expr, cell_id::Base.UUID, ends_with_semicolon::Bool, function_wrapped_info::Tuple{Set{Symbol}, Set{Symbol}})
    @ Pluto.WorkspaceManager ~\.julia\packages\Pluto\luIaC\src\evaluation\WorkspaceManager.jl:244
 [17] run_single!(session_notebook::Tuple{Pluto.ServerSession, Pluto.Notebook}, cell::Pluto.Cell, reactive_node::Pluto.ReactiveNode)
    @ Pluto ~\.julia\packages\Pluto\luIaC\src\evaluation\Run.jl:107
 [18] run_reactive!(session::Pluto.ServerSession, notebook::Pluto.Notebook, old_topology::Pluto.NotebookTopology, new_topology::Pluto.NotebookTopology, cells::Vector{Pluto.Cell}; deletion_hook::Function, persist_js_state::Bool)
    @ Pluto ~\.julia\packages\Pluto\luIaC\src\evaluation\Run.jl:78
 [19] macro expansion
    @ ~\.julia\packages\Pluto\luIaC\src\evaluation\Run.jl:13 [inlined]
 [20] (::Pluto.var"#79#81"{Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:deletion_hook, :persist_js_state), Tuple{Pluto.var"#custom_deletion_hook#190"{Pluto.var"#custom_deletion_hook#188#191"{Int64, Symbol}}, Bool}}}, Pluto.ServerSession, Pluto.Notebook, Vector{Pluto.Cell}, Pluto.NotebookTopology, Pluto.NotebookTopology})()
    @ Pluto .\task.jl:406

```

### PR DESCRIPTION
**Pull request by IanButterworth**
This fixes the MWE in #32 

I'm not sure whether it fixes the other PR, #31 though as I don't think it changes handling of `Base64EncodePipe`

@fonsp would you mind testing this?

### CODE REVIEW

**Comment by IanButterworth** [comment]
@johnnychen94 do we need to do something similar for `Base64EncodePipe` to avoid the segfault in #31 ?

**Comment by vtjnash** [comment]
Yikes. This seems like a risk with completely untyped wrappers
https://github.com/JuliaIO/PNGFiles.jl/blob/3a984f49e380994ee916239125ff430541f68b9d/gen/libpng/libpng_api.jl#L367-L368
while this looks reasonable, and the callback itself seems completely sane https://github.com/JuliaIO/PNGFiles.jl/blob/63e754f36df9040fb52477862397901e06fd104c/src/io.jl#L419-L423

There's nobody capable of holding that GC-reference to the IOContext as soon as the ccall returns. To do that, you need to instead pass a `r = Ref{Any}(io)` to the ccall, and then `GC.@preserve r ...` for the rest of the function

**Comment by IanButterworth** [comment]
I see! Thanks.. This seems to work.. did I get it right?

File: src/io.jl [hunk 1]
```diff
@@ -419,7 +421,7 @@ end
 function _writecallback(png_ptr::png_structp, data::png_bytep, length::png_size_t)::Csize_t
     a = png_get_io_ptr(png_ptr)
     io = unsafe_pointer_to_objref(a)
-    unsafe_write(io, data, length)
+    unsafe_write(io[], data, length)
```
Comment (vtjnash) [inline src/io.jl:424]: I believe you can actually fold these together, and slightly simplify the resulting operations:
```suggestion
    io = unsafe_load(Ptr{Any}(a))
    unsafe_write(io, data, length)
```

**Review by vtjnash — APPROVED** [review]
Looks great to me!

File: src/io.jl (hunk 1 above)
Comment (IanButterworth) [reply src/io.jl]: Great, yeah that works

**Comment by IanButterworth** [comment]
Thanks for the help @vtjnash 🙏🏻

**Comment by Drvi** [comment]
Wow, I tried GC.@preserve but I'd never figure out the Ref{Any} bit. Thank you!

**Comment by fonsp** [comment]
It works!!! Thank you so much!! 🌈💙✨

https://user-images.githubusercontent.com/6933510/109384634-8858c280-78ee-11eb-86c4-b8c8e6aba9db.mov
